### ISSUE TITLE
Update slides link

### ISSUE THREAD

**Issue by temporaryna** [PaNaVTEC/Clean-Contacts#19]
Could you please update slides link for v2 (english one http://es.slideshare.net/ChristianPanadero/my-way-to-clean-android-v2-english-droidcon-spain)
Don't know if there is update for spanish, and video
Thanks!

**Comment by PaNaVTEC** [comment]
Sure, thanks for the suggestion. There is no video, I gave the talk in Droidcon Spain past past year and it seems they didn't uploaded the videos but I don't know the reason :( 

https://github.com/PaNaVTEC/Clean-Contacts/commit/99426348ba03794b73ae9b10cdf44705514ab556
