### ISSUE TITLE
Clean Android without bus

### ISSUE THREAD

**Issue by mcharmas** [PaNaVTEC/Clean-Contacts#3]
Hi, I had no idea where to leave my feedback so I've created an issue. Hope it's ok.

Great work with the project. I was thinking about your solution with retaining presenters using handler hack. It's pretty clever but I have my doubts about leaking activity and that it simply doesn't work. Notice that your module (MainModule) is holding reference to MainView that is implemented by Activity. When you are retaining instance of object graph for screen rotation you are leaking activity because new Activity is created but the old one is still hold by object graph. What is worse is that presenter that should work on new instance of Activity(MainView) has the reference to the old one.

Am I missing something here? Please correct me if I am wrong.

**Comment by PaNaVTEC** [comment]
Hi Michael, thanks for the feedback, you're welcome! Anyone can give feedback here or [on the blog post](http://panavtec.me/clean-android-without-bus/).

You're correct more or less. The graph is holding a reference to the Activity when rotating (I'm working on this) but don't worry about that the "onCreate" method is setting the new Activity so the old Activity is now not referenced and then the GC can catch it. I will clean up the code when I have some time. 

About memory, you can see at memory monitor that the heap is not growing or when it grows later the GC cleans the heap and the memory is always at the same level, so I assume that there is no leak. 

I'm updating the ConfigurationKeeper with a bugfix related, keep an eye.

**Comment by mcharmas** [comment]
I haven't found comments section below your article but just now I've relised it's on the right...

I see, presenter is updated - but is pretty easy to make a mistake. One thing is presenter but another one is module that holds reference to MainView and is created only for first instance of activity and lives in between configuration changes. Only the first one activity leaks. You can find it analyzing memory dump with MAT. In this case the leak is so small that you probably won't see it in "memory analyzer".

One more thing that concerns me is ConfigurationKeeper. Is it really necessary? When user quits activity (or finishes) the instance will not be retained so object graph will be collected with the activity anyway. Retain callbacks are called only on configuration  change so won't you achieve the same effect without ConfigurationKeeper?

**Comment by PaNaVTEC** [comment]
Michael, you're totally right, now I get you.

About presenter, to avoid mistakes I created "onCreate(PresenterViewInterface)" method on the Interface. Now you can't forgive about setting the view. Maybe I can convert to an Abstract Class that sets the view automatically and sets to null in the "onCreate/onDestroy", I don't know if is better in this way, I will think about it.

About the leaks on modules, you are only leaking while rotating. When you leave an Activity, the module is setted to <null> so GC will collect it. To avoid this, just don't keep references to the Activity in the graph or on the "onDestroy" method of the activity call graph.setView(null); 

I'm not sure about ConfigurationKeeper, the main purpose of this class was to invalidate the graph when the activity is really destroyed but I think you're right. 

I created a branch "michael_feedback" with this changes, recheck the changes and tell me if it makes more sense to you now. You can also make PR's if you want :)

Thanks for the help and feedback.
