### ISSUE TITLE
ViewInjector not able to inject fragment subclasses

### ISSUE THREAD

**Issue by srodrigo** [PaNaVTEC/Clean-Contacts#6]
When I use a fragment subclass of a BaseFragment that implements a Thread decorated view, the ViewInjector.inject method doesn't inject the view, it remains null after the injection. The ViewInjector.inject method is taking the right class (the fragment subclass).

**Comment by srodrigo** [comment]
Mmm sorry, this was due to not have the updated code containing the improvements on the injector.

There is a new problem tough: if I use a presenter subclass, it throws this exception:
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType

This is caused by this method, as my presenter does not use generics (it's parent does):
  private static Class<?> getPresenterGenericClass(Object presenter) {
    return (Class<?>) ((ParameterizedType) presenter.getClass()
        .getGenericSuperclass()).getActualTypeArguments()[0];
  }

**Comment by PaNaVTEC** [comment]
Fixed. Now you can have Child Fragments/Activities and Presenters

**Comment by srodrigo** [comment]
Thanks! :)
